In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('data/results.csv', header=0)
# a= np.genfromtxt('data/results.csv', delimiter=',')

In [16]:
df

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47

In [68]:
fastDict = []
uniqueRaces = df.raceId.unique()
# print(df.iloc[[11141]])
df_no_n = df[df.fastestLapTime.str.replace("\\","") != 'N']
for rID in uniqueRaces:
    rowsByRId = df_no_n[df_no_n.raceId == rID]
    fastestLap = rowsByRId[rowsByRId.fastestLapTime == rowsByRId.fastestLapTime.min()]
    fastDict.append(fastestLap)

result = pd.concat(fastDict)
print(result)

/var/folders/hh/q1jrmqbn74j2stf45vktvy4c0000gn/T/ipykernel_50141/3310438391.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_no_n = df[df.fastestLapTime.str.replace("\\","") != 'N']

       resultId  raceId  driverId  constructorId number  grid position  \
4             5      18         5              1     23     3        5
27           28      19         2              2      3     5        6
48           49      20         5              1     23     5        5
66           67      21         8              6      1     1        1
90           91      22         8              6      1     4        3
...         ...     ...       ...            ...    ...   ...      ...
25755     25761    1092       855             51     24    14       16
25764     25770    1093       847            131     63     4        5
25783     25789    1094       847            131     63     2        4
25800     25806    1095       847            131     63     1        1
25825     25831    1096       846              1      4     7        6

      positionText  positionOrder  points  laps         time milliseconds  \
4                5              5     4.0    58      +18.014      5708630
27               6              6     3.0    56      +49.833      5528388
48               5              5     4.0    57      +26.789      5493759
66               1              1    10.0    66  1:38:19.051      5899051
90               3              3     6.0    58       +4.271      5213722
...            ...            ...     ...   ...          ...          ...
25755           16             16     0.0    28    +1:27.043     10991047
25764            5              5    11.0    56      +44.815      6176502
25783            4              4    13.0    71      +49.431      5966160
25800            1              1    26.0    71  1:38:34.044      5914044
25825            6              6     9.0    58      +56.234      5322148

      fastestLap rank fastestLapTime fastestLapSpeed  statusId
4             43    1       1:27.418         218.385         1
27            55    1       1:35.366         209.244         1
48            49    1       1:33.193         209.062         1
66            46    1       1:21.670         205.191         1
90            20    1       1:26.506         222.144         1
...          ...  ...            ...             ...       ...
25755         20    1       1:44.411         200.220         1
25764         56    1       1:38.788         200.902         1
25783         71    1       1:20.153         193.310         1
25800         61    1       1:13.785         210.237         1
25825         44    1       1:28.391         215.085         1

[365 rows x 18 columns]

In [ ]:
result.to_csv('races_fastest_times.csv', index=False)