In [1]:
import pandas as pd

In [2]:
races = pd.read_csv('data/races.csv')
results = pd.read_csv('data/results.csv')
drivers = pd.read_csv('data/drivers.csv')
constructors = pd.read_csv('data/constructors.csv')
circuits = pd.read_csv('data/circuits.csv')

In [3]:
circuits

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park
...,...,...,...,...,...,...,...,...,...
72,75,portimao,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.62670,108,http://en.wikipedia.org/wiki/Algarve_Internati...
73,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit
74,77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.63190,39.10440,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
75,78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,\N,http://en.wikipedia.org/wiki/Losail_Internatio...
76,79,miami,Miami International Autodrome,Miami,USA,25.95810,-80.23890,\N,http://en.wikipedia.org/wiki/Miami_Internation...

In [4]:
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,1116,2023,19,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00
1098,1117,2023,20,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N
1099,1118,2023,21,18,São Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00
1100,1119,2023,22,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-17,04:30:00,2023-11-17,08:00:00,2023-11-18,04:30:00,2023-11-18,08:00:00,\N,\N
1101,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N

In [5]:
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47

In [6]:
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
852,854,mick_schumacher,47,MSC,Mick,Schumacher,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher
853,855,zhou,24,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou
854,856,de_vries,45,DEV,Nyck,de Vries,1995-02-06,Dutch,http://en.wikipedia.org/wiki/Nyck_de_Vries
855,857,piastri,81,PIA,Oscar,Piastri,2001-04-06,Australian,http://en.wikipedia.org/wiki/Oscar_Piastri
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant

In [7]:
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team

In [8]:
final = results.merge(drivers[['driverId', 'driverRef', 'forename', 'surname', 'nationality']], how='left', on='driverId')
final = final.merge(constructors[['constructorId', 'name']], how='left', on='constructorId')
final = final.merge(races[['raceId', 'year', 'circuitId']], how='left', on='raceId')
final = final.merge(circuits[['circuitId', 'name']], how='left', on='circuitId', suffixes=('Team', 'Track'))

In [9]:
final

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,fastestLapSpeed,statusId,driverRef,forename,surname,nationality,nameTeam,year,circuitId,nameTrack
0,1,18,1,1,22,1,1,1,1,10.0,...,218.300,1,hamilton,Lewis,Hamilton,British,McLaren,2008,1,Albert Park Grand Prix Circuit
1,2,18,2,2,3,5,2,2,2,8.0,...,217.586,1,heidfeld,Nick,Heidfeld,German,BMW Sauber,2008,1,Albert Park Grand Prix Circuit
2,3,18,3,3,7,7,3,3,3,6.0,...,216.719,1,rosberg,Nico,Rosberg,German,Williams,2008,1,Albert Park Grand Prix Circuit
3,4,18,4,4,5,11,4,4,4,5.0,...,215.464,1,alonso,Fernando,Alonso,Spanish,Renault,2008,1,Albert Park Grand Prix Circuit
4,5,18,5,1,23,3,5,5,5,4.0,...,218.385,1,kovalainen,Heikki,Kovalainen,Finnish,McLaren,2008,1,Albert Park Grand Prix Circuit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,...,211.632,11,mick_schumacher,Mick,Schumacher,German,Haas F1 Team,2022,24,Yas Marina Circuit
25836,25842,1096,825,210,20,16,17,17,17,0.0,...,208.556,11,kevin_magnussen,Kevin,Magnussen,Danish,Haas F1 Team,2022,24,Yas Marina Circuit
25837,25843,1096,1,131,44,5,18,18,18,0.0,...,211.738,9,hamilton,Lewis,Hamilton,British,Mercedes,2022,24,Yas Marina Circuit
25838,25844,1096,849,3,6,20,19,19,19,0.0,...,210.517,130,latifi,Nicholas,Latifi,Canadian,Williams,2022,24,Yas Marina Circuit
25839,25845,1096,4,214,14,10,\N,R,20,0.0,...,209.889,47,alonso,Fernando,Alonso,Spanish,Alpine F1 Team,2022,24,Yas Marina Circuit

In [10]:
final.drop(['position', 'positionText', 'laps', 'time', 'fastestLap', 'milliseconds'], axis=1, inplace=True)

In [11]:
final

,resultId,raceId,driverId,constructorId,number,grid,positionOrder,points,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,forename,surname,nationality,nameTeam,year,circuitId,nameTrack
0,1,18,1,1,22,1,1,10.0,2,1:27.452,218.300,1,hamilton,Lewis,Hamilton,British,McLaren,2008,1,Albert Park Grand Prix Circuit
1,2,18,2,2,3,5,2,8.0,3,1:27.739,217.586,1,heidfeld,Nick,Heidfeld,German,BMW Sauber,2008,1,Albert Park Grand Prix Circuit
2,3,18,3,3,7,7,3,6.0,5,1:28.090,216.719,1,rosberg,Nico,Rosberg,German,Williams,2008,1,Albert Park Grand Prix Circuit
3,4,18,4,4,5,11,4,5.0,7,1:28.603,215.464,1,alonso,Fernando,Alonso,Spanish,Renault,2008,1,Albert Park Grand Prix Circuit
4,5,18,5,1,23,3,5,4.0,1,1:27.418,218.385,1,kovalainen,Heikki,Kovalainen,Finnish,McLaren,2008,1,Albert Park Grand Prix Circuit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,0.0,12,1:29.833,211.632,11,mick_schumacher,Mick,Schumacher,German,Haas F1 Team,2022,24,Yas Marina Circuit
25836,25842,1096,825,210,20,16,17,0.0,20,1:31.158,208.556,11,kevin_magnussen,Kevin,Magnussen,Danish,Haas F1 Team,2022,24,Yas Marina Circuit
25837,25843,1096,1,131,44,5,18,0.0,11,1:29.788,211.738,9,hamilton,Lewis,Hamilton,British,Mercedes,2022,24,Yas Marina Circuit
25838,25844,1096,849,3,6,20,19,0.0,14,1:30.309,210.517,130,latifi,Nicholas,Latifi,Canadian,Williams,2022,24,Yas Marina Circuit
25839,25845,1096,4,214,14,10,20,0.0,17,1:30.579,209.889,47,alonso,Fernando,Alonso,Spanish,Alpine F1 Team,2022,24,Yas Marina Circuit

In [12]:
final.to_csv('results_dataset.csv')

In [13]:
driverStandings = final.copy()
driverStandings

,resultId,raceId,driverId,constructorId,number,grid,positionOrder,points,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,forename,surname,nationality,nameTeam,year,circuitId,nameTrack
0,1,18,1,1,22,1,1,10.0,2,1:27.452,218.300,1,hamilton,Lewis,Hamilton,British,McLaren,2008,1,Albert Park Grand Prix Circuit
1,2,18,2,2,3,5,2,8.0,3,1:27.739,217.586,1,heidfeld,Nick,Heidfeld,German,BMW Sauber,2008,1,Albert Park Grand Prix Circuit
2,3,18,3,3,7,7,3,6.0,5,1:28.090,216.719,1,rosberg,Nico,Rosberg,German,Williams,2008,1,Albert Park Grand Prix Circuit
3,4,18,4,4,5,11,4,5.0,7,1:28.603,215.464,1,alonso,Fernando,Alonso,Spanish,Renault,2008,1,Albert Park Grand Prix Circuit
4,5,18,5,1,23,3,5,4.0,1,1:27.418,218.385,1,kovalainen,Heikki,Kovalainen,Finnish,McLaren,2008,1,Albert Park Grand Prix Circuit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,0.0,12,1:29.833,211.632,11,mick_schumacher,Mick,Schumacher,German,Haas F1 Team,2022,24,Yas Marina Circuit
25836,25842,1096,825,210,20,16,17,0.0,20,1:31.158,208.556,11,kevin_magnussen,Kevin,Magnussen,Danish,Haas F1 Team,2022,24,Yas Marina Circuit
25837,25843,1096,1,131,44,5,18,0.0,11,1:29.788,211.738,9,hamilton,Lewis,Hamilton,British,Mercedes,2022,24,Yas Marina Circuit
25838,25844,1096,849,3,6,20,19,0.0,14,1:30.309,210.517,130,latifi,Nicholas,Latifi,Canadian,Williams,2022,24,Yas Marina Circuit
25839,25845,1096,4,214,14,10,20,0.0,17,1:30.579,209.889,47,alonso,Fernando,Alonso,Spanish,Alpine F1 Team,2022,24,Yas Marina Circuit

In [14]:
driverStandings.drop(['grid','fastestLapTime', 'fastestLapSpeed'], axis=1, inplace=True)
driverStandings

,resultId,raceId,driverId,constructorId,number,positionOrder,points,rank,statusId,driverRef,forename,surname,nationality,nameTeam,year,circuitId,nameTrack
0,1,18,1,1,22,1,10.0,2,1,hamilton,Lewis,Hamilton,British,McLaren,2008,1,Albert Park Grand Prix Circuit
1,2,18,2,2,3,2,8.0,3,1,heidfeld,Nick,Heidfeld,German,BMW Sauber,2008,1,Albert Park Grand Prix Circuit
2,3,18,3,3,7,3,6.0,5,1,rosberg,Nico,Rosberg,German,Williams,2008,1,Albert Park Grand Prix Circuit
3,4,18,4,4,5,4,5.0,7,1,alonso,Fernando,Alonso,Spanish,Renault,2008,1,Albert Park Grand Prix Circuit
4,5,18,5,1,23,5,4.0,1,1,kovalainen,Heikki,Kovalainen,Finnish,McLaren,2008,1,Albert Park Grand Prix Circuit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,16,0.0,12,11,mick_schumacher,Mick,Schumacher,German,Haas F1 Team,2022,24,Yas Marina Circuit
25836,25842,1096,825,210,20,17,0.0,20,11,kevin_magnussen,Kevin,Magnussen,Danish,Haas F1 Team,2022,24,Yas Marina Circuit
25837,25843,1096,1,131,44,18,0.0,11,9,hamilton,Lewis,Hamilton,British,Mercedes,2022,24,Yas Marina Circuit
25838,25844,1096,849,3,6,19,0.0,14,130,latifi,Nicholas,Latifi,Canadian,Williams,2022,24,Yas Marina Circuit
25839,25845,1096,4,214,14,20,0.0,17,47,alonso,Fernando,Alonso,Spanish,Alpine F1 Team,2022,24,Yas Marina Circuit

In [15]:
driverStandings.drop(driverStandings.loc[driverStandings['positionOrder'] != 1].index, inplace=True)
driverStandings.reset_index(drop=True)

,resultId,raceId,driverId,constructorId,number,positionOrder,points,rank,statusId,driverRef,forename,surname,nationality,nameTeam,year,circuitId,nameTrack
0,1,18,1,1,22,1,10.0,2,1,hamilton,Lewis,Hamilton,British,McLaren,2008,1,Albert Park Grand Prix Circuit
1,23,19,8,6,1,1,10.0,2,1,raikkonen,Kimi,Räikkönen,Finnish,Ferrari,2008,2,Sepang International Circuit
2,45,20,13,6,2,1,10.0,3,1,massa,Felipe,Massa,Brazilian,Ferrari,2008,3,Bahrain International Circuit
3,67,21,8,6,1,1,10.0,1,1,raikkonen,Kimi,Räikkönen,Finnish,Ferrari,2008,4,Circuit de Barcelona-Catalunya
4,89,22,13,6,2,1,10.0,3,1,massa,Felipe,Massa,Brazilian,Ferrari,2008,5,Istanbul Park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,25746,1092,830,9,1,1,25.0,4,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,22,Suzuka Circuit
1078,25766,1093,830,9,1,1,25.0,2,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,69,Circuit of the Americas
1079,25786,1094,830,9,1,1,25.0,4,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,32,Autódromo Hermanos Rodríguez
1080,25806,1095,847,131,63,1,26.0,1,1,russell,George,Russell,British,Mercedes,2022,18,Autódromo José Carlos Pace
1081,25826,1096,830,9,1,1,25.0,6,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,24,Yas Marina Circuit

In [16]:
firstPlaceCounts = driverStandings.groupby(by=['driverRef', 'positionOrder'])
newCounts = firstPlaceCounts.size()
newCounts.to_csv('first_place_counts.csv')

In [17]:
driverStandings.to_csv('first_place_instances.csv')

In [18]:
driversUnique = driverStandings.driverRef.unique();

In [19]:
driverYearsTotal = final.groupby(by=['driverRef', 'year'])

In [20]:
driverYearsCounts = driverYearsTotal.size().groupby('driverRef').count()

In [21]:
driverYearsCounts = driverYearsCounts.to_frame()

In [22]:
type(driverYearsCounts)

pandas.core.frame.DataFrame

In [23]:
driverYearsCounts

           0
driverRef
Cannoc     1
Changy     1
abate      2
abecassis  2
acheson    2
...       ..
zapico     1
zhou       1
zonta      5
zorzi      3
zunino     3

[855 rows x 1 columns]

In [24]:
driverYearsCounts = driverYearsCounts.rename(columns={'0': 'yearCount'})

In [25]:
driverYearsCounts

           0
driverRef
Cannoc     1
Changy     1
abate      2
abecassis  2
acheson    2
...       ..
zapico     1
zhou       1
zonta      5
zorzi      3
zunino     3

[855 rows x 1 columns]

In [26]:
# final = results.merge(drivers[['driverId', 'driverRef', 'forename', 'surname', 'nationality']], how='left', on='driverId')
counts = newCounts.to_frame()
yearsWins = counts.merge(driverYearsCounts, how='left', on='driverRef')
yearsWins.columns = ['wins', 'years']

In [27]:
yearsWins

           wins  years
driverRef
alboreto      5     14
alesi         1     13
alonso       32     19
angelis       2      8
arnoux        7     12
...         ...    ...
vukovich      2      5
wallard       1      2
ward          1     11
watson        5     12
webber        9     12

[113 rows x 2 columns]

In [28]:
yearsWins.to_csv('wins_and_years.csv')

In [29]:
##edits here
driverStandings

,resultId,raceId,driverId,constructorId,number,positionOrder,points,rank,statusId,driverRef,forename,surname,nationality,nameTeam,year,circuitId,nameTrack
0,1,18,1,1,22,1,10.0,2,1,hamilton,Lewis,Hamilton,British,McLaren,2008,1,Albert Park Grand Prix Circuit
22,23,19,8,6,1,1,10.0,2,1,raikkonen,Kimi,Räikkönen,Finnish,Ferrari,2008,2,Sepang International Circuit
44,45,20,13,6,2,1,10.0,3,1,massa,Felipe,Massa,Brazilian,Ferrari,2008,3,Bahrain International Circuit
66,67,21,8,6,1,1,10.0,1,1,raikkonen,Kimi,Räikkönen,Finnish,Ferrari,2008,4,Circuit de Barcelona-Catalunya
88,89,22,13,6,2,1,10.0,3,1,massa,Felipe,Massa,Brazilian,Ferrari,2008,5,Istanbul Park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25740,25746,1092,830,9,1,1,25.0,4,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,22,Suzuka Circuit
25760,25766,1093,830,9,1,1,25.0,2,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,69,Circuit of the Americas
25780,25786,1094,830,9,1,1,25.0,4,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,32,Autódromo Hermanos Rodríguez
25800,25806,1095,847,131,63,1,26.0,1,1,russell,George,Russell,British,Mercedes,2022,18,Autódromo José Carlos Pace
25820,25826,1096,830,9,1,1,25.0,6,1,max_verstappen,Max,Verstappen,Dutch,Red Bull,2022,24,Yas Marina Circuit

In [30]:
x= driverStandings.groupby(by=['nameTrack','nameTeam'])

In [31]:
x.count()

                                    resultId  raceId  driverId  constructorId  \
nameTrack               nameTeam
AVUS                    Ferrari            1       1         1              1
Adelaide Street Circuit Benetton           1       1         1              1
                        Ferrari            1       1         1              1
                        McLaren            5       5         5              5
                        Williams           4       4         4              4
...                                      ...     ...       ...            ...
Zolder                  Ligier             1       1         1              1
                        McLaren            1       1         1              1
                        Team Lotus         2       2         2              2
                        Tyrrell            1       1         1              1
                        Williams           1       1         1              1

                                    number  positionOrder  points  rank  \
nameTrack               nameTeam
AVUS                    Ferrari          1              1       1     1
Adelaide Street Circuit Benetton         1              1       1     1
                        Ferrari          1              1       1     1
                        McLaren          5              5       5     5
                        Williams         4              4       4     4
...                                    ...            ...     ...   ...
Zolder                  Ligier           1              1       1     1
                        McLaren          1              1       1     1
                        Team Lotus       2              2       2     2
                        Tyrrell          1              1       1     1
                        Williams         1              1       1     1

                                    statusId  driverRef  forename  surname  \
nameTrack               nameTeam
AVUS                    Ferrari            1          1         1        1
Adelaide Street Circuit Benetton           1          1         1        1
                        Ferrari            1          1         1        1
                        McLaren            5          5         5        5
                        Williams           4          4         4        4
...                                      ...        ...       ...      ...
Zolder                  Ligier             1          1         1        1
                        McLaren            1          1         1        1
                        Team Lotus         2          2         2        2
                        Tyrrell            1          1         1        1
                        Williams           1          1         1        1

                                    nationality  year  circuitId
nameTrack               nameTeam
AVUS                    Ferrari               1     1          1
Adelaide Street Circuit Benetton              1     1          1
                        Ferrari               1     1          1
                        McLaren               5     5          5
                        Williams              4     4          4
...                                         ...   ...        ...
Zolder                  Ligier                1     1          1
                        McLaren               1     1          1
                        Team Lotus            2     2          2
                        Tyrrell               1     1          1
                        Williams              1     1          1

[427 rows x 15 columns]

In [32]:
x.count().to_csv('test.csv')