In [1]:
import pandas as pd

In [2]:
races = pd.read_csv('data/races.csv')
results = pd.read_csv('data/results.csv')
drivers = pd.read_csv('data/drivers.csv')
constructors = pd.read_csv('data/constructors.csv')

In [3]:
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,1116,2023,19,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00
1098,1117,2023,20,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N
1099,1118,2023,21,18,SÃ£o Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00
1100,1119,2023,22,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-17,04:30:00,2023-11-17,08:00:00,2023-11-18,04:30:00,2023-11-18,08:00:00,\N,\N
1101,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N

In [4]:
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47

In [5]:
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
852,854,mick_schumacher,47,MSC,Mick,Schumacher,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher
853,855,zhou,24,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou
854,856,de_vries,45,DEV,Nyck,de Vries,1995-02-06,Dutch,http://en.wikipedia.org/wiki/Nyck_de_Vries
855,857,piastri,81,PIA,Oscar,Piastri,2001-04-06,Australian,http://en.wikipedia.org/wiki/Oscar_Piastri
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant

In [6]:
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team

In [7]:
final = results.merge(drivers[['driverId', 'driverRef', 'nationality']], how='left', on='driverId')
final = final.merge(constructors[['constructorId', 'constructorRef']], how='left', on='constructorId')
final = final.merge(races[['raceId', 'year', 'name', 'circuitId']], how='left', on='raceId')

In [8]:
final

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,nationality,constructorRef,year,name,circuitId
0,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,hamilton,British,mclaren,2008,Australian Grand Prix,1
1,2,18,2,2,3,5,2,2,2,8.0,...,3,1:27.739,217.586,1,heidfeld,German,bmw_sauber,2008,Australian Grand Prix,1
2,3,18,3,3,7,7,3,3,3,6.0,...,5,1:28.090,216.719,1,rosberg,German,williams,2008,Australian Grand Prix,1
3,4,18,4,4,5,11,4,4,4,5.0,...,7,1:28.603,215.464,1,alonso,Spanish,renault,2008,Australian Grand Prix,1
4,5,18,5,1,23,3,5,5,5,4.0,...,1,1:27.418,218.385,1,kovalainen,Finnish,mclaren,2008,Australian Grand Prix,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,...,12,1:29.833,211.632,11,mick_schumacher,German,haas,2022,Abu Dhabi Grand Prix,24
25836,25842,1096,825,210,20,16,17,17,17,0.0,...,20,1:31.158,208.556,11,kevin_magnussen,Danish,haas,2022,Abu Dhabi Grand Prix,24
25837,25843,1096,1,131,44,5,18,18,18,0.0,...,11,1:29.788,211.738,9,hamilton,British,mercedes,2022,Abu Dhabi Grand Prix,24
25838,25844,1096,849,3,6,20,19,19,19,0.0,...,14,1:30.309,210.517,130,latifi,Canadian,williams,2022,Abu Dhabi Grand Prix,24
25839,25845,1096,4,214,14,10,\N,R,20,0.0,...,17,1:30.579,209.889,47,alonso,Spanish,alpine,2022,Abu Dhabi Grand Prix,24

In [9]:
final.drop(['position', 'positionText', 'laps', 'time', 'fastestLap', 'milliseconds'], axis=1, inplace=True)

In [10]:
final

,resultId,raceId,driverId,constructorId,number,grid,positionOrder,points,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,nationality,constructorRef,year,name,circuitId
0,1,18,1,1,22,1,1,10.0,2,1:27.452,218.300,1,hamilton,British,mclaren,2008,Australian Grand Prix,1
1,2,18,2,2,3,5,2,8.0,3,1:27.739,217.586,1,heidfeld,German,bmw_sauber,2008,Australian Grand Prix,1
2,3,18,3,3,7,7,3,6.0,5,1:28.090,216.719,1,rosberg,German,williams,2008,Australian Grand Prix,1
3,4,18,4,4,5,11,4,5.0,7,1:28.603,215.464,1,alonso,Spanish,renault,2008,Australian Grand Prix,1
4,5,18,5,1,23,3,5,4.0,1,1:27.418,218.385,1,kovalainen,Finnish,mclaren,2008,Australian Grand Prix,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,0.0,12,1:29.833,211.632,11,mick_schumacher,German,haas,2022,Abu Dhabi Grand Prix,24
25836,25842,1096,825,210,20,16,17,0.0,20,1:31.158,208.556,11,kevin_magnussen,Danish,haas,2022,Abu Dhabi Grand Prix,24
25837,25843,1096,1,131,44,5,18,0.0,11,1:29.788,211.738,9,hamilton,British,mercedes,2022,Abu Dhabi Grand Prix,24
25838,25844,1096,849,3,6,20,19,0.0,14,1:30.309,210.517,130,latifi,Canadian,williams,2022,Abu Dhabi Grand Prix,24
25839,25845,1096,4,214,14,10,20,0.0,17,1:30.579,209.889,47,alonso,Spanish,alpine,2022,Abu Dhabi Grand Prix,24

In [14]:
final.to_csv('results_dataset.csv')